site_name: Rick-Mailer
site_url: https://git.oddbit.org/OddBit/rick-mailer
repo_url: https://git.oddbit.org/OddBit/rick-mailer
repo_name: OddBit/rick-mailer
nav:
  - Tutorial: index.md

theme:
  name: material
  palette:
    scheme: preference
    primary: indigo
    accent: indigo
  language: en

markdown_extensions:
  - pymdownx.highlight:
      linenums: false
      linenums_style: pymdownx.inline
  - pymdownx.superfences
  - pymdownx.inlinehilite
plugins:
  - include-markdown
  - search:
      lang: en

